---
title: "report_analysis"
author: "Stephanie Boettiger"
date: '2022-04-04'
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
source("calc_effectsizes.R")
source("analysis.R")
```

```{r}
# results
res
```

```{r}
# pooled correlation estimate

predict(res, transf = transf.ztor)
```

```{r}
confint(res)
```

```{r}
res2 
res3
```

```{r}
# PEESE test (similar to Egger's)

test.egger
```

```{r}
# Precision effect test

PET
```

```{r}
#Cook's distance 
x
plot(x, type = "o",
     pch = 19,
     xlab = "Observed Outcome",
     ylab = "Cook's Distance"
    ) 
```

```{r}
hatvalues.rma.mv(res)
plot(hatvalues.rma.mv(res))
```

```{r}
# visualizations
forest(res)
```

```{r}
forest_df %>%  
  ggplot(.,
          aes(x = yi,
              y = study_id,
              xmin = lowerci,
              xmax = upperci)) +
  geom_point(shape = 18,
             size = 4, 
             color = "black"
             ) + 
  scale_x_continuous(limits = c(-.4, .6), 
                     breaks = c(-.4, -.3, -.2, -.1, 0, .1, .2, .3, .4, .5, .6),
                     name = "Correlation Coefficient (r)") +
  ylab("Author(s)") + 
  scale_y_continuous(
    limits = c(1, length(forest_df$study_id)),
    breaks = 1:length(forest_df$study_id)
  ) + 
  geom_vline(xintercept = 0, 
             color = "black", 
             linetype = "dashed")
 
p1

```
```{r}
ggsave(p1, filename = "ggforestp1.png", width = 8, height = 8, dpi = 300)
```

```{r}
res2 <- res
res2$vi.f <- res2$vi.f[1:28]
forest(res2, 
       xlim = c(- .5, .9), 
       atransf = transf.ztor, 
       addpred=TRUE, 
       header=TRUE,
       at=transf.ztor(c(-.4, -.2, 0, .2, .4, .6)), 
       digits=c(2,1), cex = .5)
```


```{r}
res3 <- res
res3$vi.f <- res3$vi.f[29:57]
res3$yi.f <- res3$yi.f[29:57]
res3$slab <- res3$slab[29:57]
forest(res3, xlim = c(-3, 4))
```


```{r}
res4 <- res
res4$vi.f <- res4$vi.f[58:86]
res4$yi.f <- res4$yi.f[58:86]
res4$slab <- res4$slab[58:86]
forest(res4, xlim = c(-3, 4))
```


```{r}
res5 <- res
res5$vi.f <- res4$vi.f[87:115]
res5$yi.f <- res4$yi.f[87:115]
res5$slab <- res4$slab[87:115]
forest(res5, xlim = c(-3, 4))
```


```{r}
res6 <- res
res5$vi.f <- res4$vi.f[116:144]
res5$yi.f <- res4$yi.f[116:144]
res5$slab <- res4$slab[116:144]
```

```{r}
res7 <- res
res5$vi.f <- res4$vi.f[145:173]
res5$yi.f <- res4$yi.f[145:173]
res5$slab <- res4$slab[145:173]
forest(res6, xlim = c(-3, 4))
```

```{r}
res8 <- res
res8$vi.f <- res4$vi.f[174:196]
res8$yi.f <- res4$yi.f[174:196]
res8$slab <- res4$slab[174:196]
forest(res6, xlim = c(-3, 4))
```


```{r}
# alternative
forest_df
```

```{r}
#study bias - plot to show asymmetry
funnel(res)
```

```{r}
# prettier funnel plot (in the works)

estimate = 0.1199
se = 0.0220

se.seq = seq(0, max(meta$vi), 0.001)

ll95 = estimate-(1.96*se.seq)
ul95 = estimate+(1.96*se.seq)

ll99 = estimate-(3.96*se.seq)
ul99 = estimate+(3.96*se.seq)

meanll95 = estimate-(1.96*se)
meanul95 = estimate+(1.96*se)

dfCI <- data.frame(ll95, ul95, ll99, ul99, se.seq, estimate, meanll95, meanul95)

fp <- ggplot(aes(x = se,
                 y = Zr,
                 data = res)
) +
  geom_point(shape = 1) +
  xlab = ('Standard Error') +
  ylab = ('Zr') +
  geom_line(aes(x = se.seq, 
                y = ll95), 
                linetype = 'dotted', 
                data = dfCI) +
  geom_line(aes(x = se.seq, 
                y = ul95), 
                linetype = 'dotted', 
                data = dfCI) +
  geom_line(aes(x = se.seq, 
                y = ll99), 
                linetype = 'dashed', 
                data = dfCI) +
  geom_line(aes(x = se.seq, 
                y = ul99), 
                linetype = 'dashed', 
                data = dfCI) +
  geom_segment(aes(x = min(se.seq), 
                   y = meanll95, 
                   xend = max(se.seq), 
                   yend = meanll95), 
                   linetype='dotted', 
                   data=dfCI) +
  geom_segment(aes(x = min(se.seq), 
                   y = meanul95, 
                   xend = max(se.seq), 
                   yend = meanul95), 
                   linetype='dotted', 
                   data=dfCI) +
  scale_x_reverse() +
  scale_y_continuous(breaks=seq(-.4,.6,0.5)) +
  coord_flip() +
  theme_bw()
```


# moderation analysis ---------------------------------------------------------

res_mod <- rma(yi, vi, 
               mods =~ factor(cm_measure) + 
                 cbind(age_mean + age_min + age_max + gender)
) 

```

